services:
  fastapi-fullstack-starter_database:
    image: postgres:16
    container_name: fastapi-fullstack-starter_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  fastapi-fullstack-starter_app:
    image: fastapi-fullstack-starter_app
    container_name: fastapi-fullstack-starter_app
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - fastapi-fullstack-starter_database
    env_file:
      - .env

volumes:
  pgdata: